version: '3.9'

services:
  app:
    build: .
    restart: always
    container_name: utils
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
